### ISSUE TITLE
Failed to draw char tab

### ISSUE THREAD

**Issue by Reiketsuna94** [PassiveModding/Meddle#10]
I try to export all models with attaches and allways get an information failed to draw char tab.

![Screenshot 2024-08-20 223551](https://github.com/user-attachments/assets/a5f391c8-719a-4ef0-a8b5-b57f85a08fa4)

**Comment by Reiketsuna94** [comment]
![Screenshot 2024-08-20 224124](https://github.com/user-attachments/assets/88b3cdfe-6eac-4b56-b566-8f9c5029bc2d)

**Comment by PassiveModding** [comment]
This was caused by the path containing non-standard characters. a fix should be available for this from v0.1.15. However this mod may still have issues related to the materials. Please create a separate issue if you experience it. Thanks
