### ISSUE TITLE
Transparent mesh

### ISSUE THREAD

**Issue by Ersk91** [PassiveModding/Meddle#16]
I've being having this weird issue with export characters in meddle where the mesh of some modded items is there but is not visible. It happens with both gear and hair. 
Altho even if the results is the same it seems to be related to different problems.
on the hair the UVs are broken
![GWuhxBOXMAACLoi](https://github.com/user-attachments/assets/07760157-ab4f-40a0-8653-dcef74a29663)
![GWuhxBPWgAAmJue](https://github.com/user-attachments/assets/093185a2-75b2-41e9-92fa-6dd951d54283)

on the neck the textures are exported wrongly
![GWuhxBQWUAA4PX4](https://github.com/user-attachments/assets/98448e93-4bc7-4f8a-b52a-45467da705b2)
![GWuhxBaWQAAJHC9](https://github.com/user-attachments/assets/cee19bf8-cb14-4e71-8e39-a6cfc4dba84b)

I tried importing directly from textool and there were no issue at all. Also most of this issues seems to be related with updated items for DT, despite the new ones working just fine.
I tried different mods and items, thinking it may have been the specific item in question, but I end up with the same issue in more items, even from different creators or from the game itself.

Is this a setting issue? or an Item issue? It sounded weird because some items does work, and other do not, even coming from the same source.

**Comment by PassiveModding** [comment]
Issue should be resolved as of https://github.com/PassiveModding/Meddle/commit/8f51ee5f1558190dc6b927b1661a970c1a89a101
