### ISSUE TITLE
Feature Suggestion: raw texture exports

### ISSUE THREAD

**Issue by theta5** [PassiveModding/Meddle#2]
Would there be a way to get this to export the textures as the game reads them in the main export in addition to the compiled versions, for compatibility with the colorsetter and WoL shader Blender addons? Most items have a colorset, multi map, and normal instead of diffuse, specular, and normal, and currently color data is lost in converting from those.

**Comment by PassiveModding** [comment]
This should be supported for all versions > v0.1.0 with two options
- Export Raw Textures; will export all textures for a given character
- Export Individual Texture; can be found if you expand into the texture preview menu
