### ISSUE TITLE
<3

### ISSUE THREAD

**Issue by jtabox** [PassiveModding/Meddle#3]
Not an issue, I just wanted to say *THANK YOU*!

I've been looking for a plugin that does exactly what this does and was becoming a bit frustrated because I couldn't find one. I even started looking how to write my own, but this functionality is way out of my league.

Thanks again, curious to see how this plugin develops with more functionality (if it's something you're planning, otherwise I'm perfectly content with its current state 😄 ).

**Comment by PassiveModding** [comment]
I appreciate the kind words, hope you enjoy using it and feel free to raise other issues for feature requests or bug reports.
