### ISSUE TITLE
FR: Add custom save name option

### ISSUE THREAD

**Issue by Akurosia** [PassiveModding/Meddle#6]
I really love this plugin, 1 of the features i am missing is a more explaining name for the export. 
i would like to be able to allow names e.g. from zone, entity etc.

My prefered option would be:
make toggle in the options tab to include zone > Meddle.Export/output/ZONENAME/timestamp
make toggle in the options tab to include entity_name > Meddle.Export/output/ENTITYNAME/timestamp
make toggle in the options tab to include entity_type (e.g. human, monster) > Meddle.Export/output/ENTITYTYPE/timestamp
(if there are more types also including the Player keyword or BattleNPCs or replace the entity_type with this one)

If all are checked just concat them e.g. : Meddle.Export/output/ZONENAME/ENTITYTYPE/ENTITYNAME/timestamp

**Comment by PassiveModding** [comment]
Model exports now support specifying a custom name during export
