### ISSUE TITLE
FR: Option to "automaticly" export unique monster/npc based on ".mdl" file

### ISSUE THREAD

**Issue by Akurosia** [PassiveModding/Meddle#7]
i would like a feature to export all unique mobs of a content.
My setup would be: join an instance (dungeon, trial etc) turn on plugin option to export everything uniqely and run through the content.

Expected behaviour: 
For every mob only 1 export was done based on the mdl file

Small bonus love points: If this would be able do be done to also include the naming feature from https://github.com/PassiveModding/Meddle/issues/6 to have a sorted folder in the end

**Comment by PassiveModding** [comment]
This functionality is outside of the scope of the plugin, though feel free to fork and tweak behavior to something which may suit your use-case more
