### ISSUE TITLE
ERR/FR: World Tab: Error Drawing Overlay

### ISSUE THREAD

**Issue by Gold-Shogun** [PassiveModding/Meddle#9]
Trying out the world tab (I understand that it's still in testing), but opening that tab just gives me constant "Error Drawing Overlay" Errors. Clean install of Meddle, just wanted to try out the new tab, as 3D FF14 animators have been franticly looking for a zone exporter since Dawntrail released, and the old tool for exporting zones was discontinued.

Once more testing is done, will there be an option to export full zones?

![Screenshot 2024-08-17 155402](https://github.com/user-attachments/assets/9b9154eb-973e-4249-84f9-2d3edd1ed2eb)

**Comment by kajupe** [comment]
Full zone export would be absolutely incredible in the future, if that is possible with this type of tech.

**Comment by PassiveModding** [comment]
@Gold-Shogun if you can, check `/xllog` and attach a screenshot or copy of the error message here

**Comment by PassiveModding** [comment]
and zone export may be supported down the track, but it's not a primary focus at the moment

**Comment by Gold-Shogun** [comment]
@PassiveModding 
![Screenshot 2024-08-18 001939](https://github.com/user-attachments/assets/d23201e3-e7fc-4769-9c1a-11647a543b47)
This is what I get in the error logs! 

And awesome, glad to know it's being considered. All of the FF14 3D animators are counting on something a tool like that eventually.

**Comment by PassiveModding** [comment]
let me know if the issue persists after v0.1.13.1, I believe it should be addressed now but I don't have a solid way of confirming it on my end

**Comment by Gold-Shogun** [comment]
> let me know if the issue persists after v0.1.13.1, I believe it should be addressed now but I don't have a solid way of confirming it on my end

Seems to be working as intended now! It exports things really nicely; textures also seem to be working well. Obviously, it's only the objects and not the terrain (as expected), but it's looking good on my end!
![Screenshot 2024-08-18 133411](https://github.com/user-attachments/assets/866951d4-8678-4d7e-83f3-fa4392a0d51b)

**Comment by Reiketsuna94** [comment]
How does it work it allways downloads a 1kb file for me @Gold-Shogun. Could we write maybe in dc?

**Comment by Gold-Shogun** [comment]
> How does it work it allways downloads a 1kb file for me @Gold-Shogun. Could we write maybe in dc?

by this do you mean Discord? @Reiketsuna94 if so, how do I add you?
